version: "3"
services:
  docsrv:
    image: onlyoffice/documentserver
    container_name: onlyoffice
    ports:
      - "9443:443"
      - "980:80"
    volumes:
      - ./log/:/var/log/onlyoffice:rw
      - ./onlyoffice/:/var/www/:rw
    networks:
      - net-onlyoffice
  nginx:
    image: nginx:alpine
    container_name: onlyoffice-nginx
    ports:
      - "9980:980"
      - "99443:9443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-nginx
networks:
  net-onlyoffice:
  net-nginx: